#!/usr/bin/env python3
"""Show the verified ROC figure generated by the shared final pipeline."""
from pathlib import Path
import json, sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from src.verification import verify_results
if __name__=='__main__':
    try:
        result=json.loads((ROOT/'reports/tables/headline_results.json').read_text())
        verify_results(result,ROOT/'reports',ROOT)
        print(ROOT/'reports/figures/figure12_roc_curves.png')
    except (OSError,ValueError,KeyError) as e:
        print(f'Run python final_pipeline.py first: {e}',file=sys.stderr)
        raise SystemExit(1)
